Object.defineProperty(exports, "__esModule", {
    value: !0
}), exports.default = {
    areaList: [ {
        area: "中国",
        code: "86"
    }, {
        area: "中国澳门",
        code: "853"
    }, {
        area: "中国香港",
        code: "852"
    }, {
        area: "中国台湾",
        code: "886"
    }, {
        area: "阿尔巴尼亚",
        code: "355"
    }, {
        area: "阿尔及利亚",
        code: "213"
    }, {
        area: "阿富汗",
        code: "93"
    }, {
        area: "阿根廷",
        code: "54"
    }, {
        area: "阿拉伯联合酋长国",
        code: "971"
    }, {
        area: "阿鲁巴岛",
        code: "297"
    }, {
        area: "阿曼",
        code: "968"
    }, {
        area: "阿塞拜疆",
        code: "994"
    }, {
        area: "阿森松岛",
        code: "247"
    }, {
        area: "埃及",
        code: "20"
    }, {
        area: "埃塞俄比亚",
        code: "251"
    }, {
        area: "爱尔兰",
        code: "353"
    }, {
        area: "爱沙尼亚",
        code: "372"
    }, {
        area: "安道尔",
        code: "376"
    }, {
        area: "安哥拉",
        code: "244"
    }, {
        area: "安圭拉岛",
        code: "1264"
    }, {
        area: "安提瓜和巴布达",
        code: "1268"
    }, {
        area: "奥地利",
        code: "43"
    }, {
        area: "澳大利亚",
        code: "61"
    }, {
        area: "巴巴多斯",
        code: "1246"
    }, {
        area: "巴布亚新几内亚",
        code: "675"
    }, {
        area: "巴哈马",
        code: "1242"
    }, {
        area: "巴基斯坦",
        code: "92"
    }, {
        area: "巴拉圭",
        code: "595"
    }, {
        area: "巴勒斯坦",
        code: "970"
    }, {
        area: "巴林",
        code: "973"
    }, {
        area: "巴拿马",
        code: "507"
    }, {
        area: "巴西",
        code: "55"
    }, {
        area: "白俄罗斯",
        code: "375"
    }, {
        area: "百慕大",
        code: "1441"
    }, {
        area: "保加利亚",
        code: "359"
    }, {
        area: "北马里亚纳群岛",
        code: "1"
    }, {
        area: "贝宁",
        code: "229"
    }, {
        area: "比利时",
        code: "32"
    }, {
        area: "冰岛",
        code: "354"
    }, {
        area: "波多黎各",
        code: "1787"
    }, {
        area: "波黑",
        code: "387"
    }, {
        area: "波兰",
        code: "48"
    }, {
        area: "玻利维亚",
        code: "591"
    }, {
        area: "伯利兹",
        code: "501"
    }, {
        area: "博茨瓦纳",
        code: "267"
    }, {
        area: "博奈尔岛、圣尤斯特歇斯和萨巴岛",
        code: "599"
    }, {
        area: "不丹",
        code: "975"
    }, {
        area: "布基纳法索",
        code: "226"
    }, {
        area: "布隆迪",
        code: "257"
    }, {
        area: "朝鲜",
        code: "850"
    }, {
        area: "赤道几内亚",
        code: "240"
    }, {
        area: "丹麦",
        code: "45"
    }, {
        area: "德国",
        code: "49"
    }, {
        area: "迪戈加西亚岛",
        code: "246"
    }, {
        area: "东帝汶",
        code: "670"
    }, {
        area: "多哥",
        code: "228"
    }, {
        area: "多米尼加",
        code: "1767"
    }, {
        area: "多米尼加共和国",
        code: "1809"
    }, {
        area: "俄罗斯",
        code: "7"
    }, {
        area: "厄瓜多尔",
        code: "593"
    }, {
        area: "厄立特里亚",
        code: "291"
    }, {
        area: "法国",
        code: "33"
    }, {
        area: "法罗群岛",
        code: "298"
    }, {
        area: "法属波利尼西亚",
        code: "689"
    }, {
        area: "法属圭亚那",
        code: "594"
    }, {
        area: "梵蒂冈",
        code: "379"
    }, {
        area: "菲律宾",
        code: "63"
    }, {
        area: "斐济",
        code: "679"
    }, {
        area: "芬兰",
        code: "358"
    }, {
        area: "佛得角",
        code: "238"
    }, {
        area: "福克兰群岛",
        code: "500"
    }, {
        area: "冈比亚",
        code: "220"
    }, {
        area: "刚果",
        code: "242"
    }, {
        area: "刚果民主共和国",
        code: "243"
    }, {
        area: "哥伦比亚",
        code: "57"
    }, {
        area: "哥斯达黎加",
        code: "506"
    }, {
        area: "格林纳达",
        code: "1473"
    }, {
        area: "格陵兰",
        code: "299"
    }, {
        area: "格鲁吉亚",
        code: "995"
    }, {
        area: "古巴",
        code: "53"
    }, {
        area: "瓜德罗普",
        code: "590"
    }, {
        area: "关岛",
        code: "1671"
    }, {
        area: "圭亚那",
        code: "592"
    }, {
        area: "哈萨克斯坦",
        code: "7"
    }, {
        area: "海地",
        code: "509"
    }, {
        area: "韩国",
        code: "82"
    }, {
        area: "荷兰",
        code: "31"
    }, {
        area: "荷属圣马丁",
        code: "1721"
    }, {
        area: "黑山",
        code: "382"
    }, {
        area: "洪都拉斯",
        code: "504"
    }, {
        area: "基里巴斯",
        code: "686"
    }, {
        area: "吉布提",
        code: "253"
    }, {
        area: "吉尔吉斯斯坦",
        code: "996"
    }, {
        area: "几内亚",
        code: "224"
    }, {
        area: "几内亚比绍",
        code: "245"
    }, {
        area: "加拿大",
        code: "1"
    }, {
        area: "加纳",
        code: "233"
    }, {
        area: "加蓬",
        code: "241"
    }, {
        area: "柬埔寨",
        code: "855"
    }, {
        area: "捷克共和国",
        code: "420"
    }, {
        area: "津巴布韦",
        code: "263"
    }, {
        area: "喀麦隆",
        code: "237"
    }, {
        area: "卡塔尔",
        code: "974"
    }, {
        area: "开曼群岛",
        code: "1345"
    }, {
        area: "科摩罗和马约特岛",
        code: "269"
    }, {
        area: "科特迪瓦",
        code: "225"
    }, {
        area: "科威特",
        code: "965"
    }, {
        area: "克罗地亚",
        code: "385"
    }, {
        area: "肯尼亚",
        code: "254"
    }, {
        area: "库克群岛",
        code: "682"
    }, {
        area: "库拉索",
        code: "599"
    }, {
        area: "拉脱维亚",
        code: "371"
    }, {
        area: "莱索托",
        code: "266"
    }, {
        area: "老挝",
        code: "856"
    }, {
        area: "黎巴嫩",
        code: "961"
    }, {
        area: "立陶宛",
        code: "370"
    }, {
        area: "利比里亚",
        code: "231"
    }, {
        area: "利比亚",
        code: "218"
    }, {
        area: "列支敦士登",
        code: "423"
    }, {
        area: "留尼旺岛",
        code: "262"
    }, {
        area: "卢森堡",
        code: "352"
    }, {
        area: "卢旺达",
        code: "250"
    }, {
        area: "罗马尼亚",
        code: "40"
    }, {
        area: "马达加斯加",
        code: "261"
    }, {
        area: "马尔代夫",
        code: "960"
    }, {
        area: "马耳他",
        code: "356"
    }, {
        area: "马拉维",
        code: "265"
    }, {
        area: "马来西亚",
        code: "60"
    }, {
        area: "马里",
        code: "223"
    }, {
        area: "马其顿",
        code: "389"
    }, {
        area: "马绍尔群岛",
        code: "692"
    }, {
        area: "马提尼克岛",
        code: "596"
    }, {
        area: "毛里求斯",
        code: "230"
    }, {
        area: "毛里塔尼亚",
        code: "222"
    }, {
        area: "美国",
        code: "1"
    }, {
        area: "美属萨摩亚",
        code: "1684"
    }, {
        area: "美属维尔京群岛",
        code: "1340"
    }, {
        area: "蒙古",
        code: "976"
    }, {
        area: "蒙特塞拉特岛",
        code: "1664"
    }, {
        area: "孟加拉国",
        code: "880"
    }, {
        area: "秘鲁",
        code: "51"
    }, {
        area: "密克罗尼西亚",
        code: "691"
    }, {
        area: "缅甸",
        code: "95"
    }, {
        area: "摩尔多瓦",
        code: "373"
    }, {
        area: "摩洛哥",
        code: "212"
    }, {
        area: "摩纳哥",
        code: "377"
    }, {
        area: "莫桑比克",
        code: "258"
    }, {
        area: "墨西哥",
        code: "52"
    }, {
        area: "纳米比亚",
        code: "264"
    }, {
        area: "南非",
        code: "27"
    }, {
        area: "南苏丹",
        code: "211"
    }, {
        area: "瑙鲁",
        code: "674"
    }, {
        area: "尼加拉瓜",
        code: "505"
    }, {
        area: "尼泊尔",
        code: "977"
    }, {
        area: "尼日尔",
        code: "227"
    }, {
        area: "尼日利亚",
        code: "234"
    }, {
        area: "纽埃岛",
        code: "683"
    }, {
        area: "挪威",
        code: "47"
    }, {
        area: "诺福克岛",
        code: "6723"
    }, {
        area: "帕劳",
        code: "680"
    }, {
        area: "葡萄牙",
        code: "351"
    }, {
        area: "日本",
        code: "81"
    }, {
        area: "瑞典",
        code: "46"
    }, {
        area: "瑞士",
        code: "41"
    }, {
        area: "萨尔瓦多",
        code: "503"
    }, {
        area: "萨摩亚",
        code: "685"
    }, {
        area: "塞尔维亚",
        code: "381"
    }, {
        area: "塞拉利昂",
        code: "232"
    }, {
        area: "塞内加尔",
        code: "221"
    }, {
        area: "塞浦路斯",
        code: "357"
    }, {
        area: "塞舌尔",
        code: "248"
    }, {
        area: "沙特阿拉伯",
        code: "966"
    }, {
        area: "圣巴泰勒米岛",
        code: "590"
    }, {
        area: "圣多美和普林西比",
        code: "239"
    }, {
        area: "圣赫勒拿岛",
        code: "290"
    }, {
        area: "圣基茨和尼维斯",
        code: "1869"
    }, {
        area: "圣卢西亚",
        code: "1758"
    }, {
        area: "圣马丁",
        code: "590"
    }, {
        area: "圣马力诺",
        code: "378"
    }, {
        area: "圣皮埃尔和密克隆群岛",
        code: "508"
    }, {
        area: "圣文森特和格林纳丁斯",
        code: "1784"
    }, {
        area: "斯里兰卡",
        code: "94"
    }, {
        area: "斯洛伐克",
        code: "421"
    }, {
        area: "斯洛文尼亚",
        code: "386"
    }, {
        area: "斯威士兰",
        code: "268"
    }, {
        area: "苏丹",
        code: "249"
    }, {
        area: "苏里南",
        code: "597"
    }, {
        area: "所罗门群岛",
        code: "677"
    }, {
        area: "索马里",
        code: "252"
    }, {
        area: "塔吉克斯坦",
        code: "992"
    }, {
        area: "泰国",
        code: "66"
    }, {
        area: "坦桑尼亚",
        code: "255"
    }, {
        area: "汤加",
        code: "676"
    }, {
        area: "特克斯和凯科斯群岛",
        code: "1649"
    }, {
        area: "特立尼达和多巴哥",
        code: "1868"
    }, {
        area: "突尼斯",
        code: "216"
    }, {
        area: "图瓦卢",
        code: "688"
    }, {
        area: "土耳其",
        code: "90"
    }, {
        area: "土库曼斯坦",
        code: "993"
    }, {
        area: "托克劳",
        code: "690"
    }, {
        area: "瓦利斯和富图纳群岛",
        code: "681"
    }, {
        area: "瓦努阿图",
        code: "678"
    }, {
        area: "危地马拉",
        code: "502"
    }, {
        area: "委内瑞拉",
        code: "58"
    }, {
        area: "文莱",
        code: "673"
    }, {
        area: "乌干达",
        code: "256"
    }, {
        area: "乌克兰语",
        code: "380"
    }, {
        area: "乌拉圭",
        code: "598"
    }, {
        area: "乌兹别克斯坦",
        code: "998"
    }, {
        area: "希腊",
        code: "30"
    }, {
        area: "西班牙",
        code: "34"
    }, {
        area: "新加坡",
        code: "65"
    }, {
        area: "新喀里多尼亚",
        code: "687"
    }, {
        area: "新西兰",
        code: "64"
    }, {
        area: "匈牙利",
        code: "36"
    }, {
        area: "叙利亚",
        code: "963"
    }, {
        area: "牙买加",
        code: "1876"
    }, {
        area: "亚美尼亚",
        code: "374"
    }, {
        area: "也门",
        code: "967"
    }, {
        area: "伊拉克",
        code: "964"
    }, {
        area: "伊朗",
        code: "98"
    }, {
        area: "以色列",
        code: "972"
    }, {
        area: "意大利",
        code: "39"
    }, {
        area: "印度",
        code: "91"
    }, {
        area: "印度尼西亚",
        code: "62"
    }, {
        area: "英国",
        code: "44"
    }, {
        area: "英属维尔京群岛",
        code: "1284"
    }, {
        area: "约旦",
        code: "962"
    }, {
        area: "越南",
        code: "84"
    }, {
        area: "赞比亚",
        code: "260"
    }, {
        area: "乍得",
        code: "235"
    }, {
        area: "直布罗陀",
        code: "350"
    }, {
        area: "智利",
        code: "56"
    }, {
        area: "中非共和国",
        code: "236"
    } ]
};