Object.defineProperty(exports, "__esModule", {
    value: !0
}), exports.ACJ_TYPES = void 0, exports.addCallback = function(_, A) {
    _ && A && (O[_] = A);
}, exports.reset = function() {
    O = {};
}, exports.acj = function(_) {
    if (_) try {
        if (A.emit && "function" == typeof A.emit) {
            o.log("call js", _);
            for (var O = arguments.length, a = Array(O > 1 ? O - 1 : 0), L = 1; L < O; L++) a[L - 1] = arguments[L];
            A.emit([ _ ].concat(a || []));
        }
    } catch (_) {
        o.warn("call acj error : ", _);
    }
}, exports.onACJ = function(_) {
    o.log("js call", _);
    var A = O[_];
    if (A && "function" == typeof A) {
        for (var a = arguments.length, L = Array(a > 1 ? a - 1 : 0), C = 1; C < a; C++) L[C - 1] = arguments[C];
        return A.apply(void 0, L);
    }
};

var _ = require("./logger"), A = getApp(), o = (0, _.makeLogger)("ACJ"), O = (exports.ACJ_TYPES = {
    CALL_BUS_SHILD: "room_bus_shild",
    CALL_TCP_LOGIN: "room_bus_login",
    CALL_SHOW_LOGIN: "room_login_show",
    CALL_SHOW_REG: "room_reg_show",
    CALL_BUS_PAGESCREEN: "room_bus_pagescr",
    CALL_OPEN_NOBLE: "room_data_openNoble",
    CALL_SHOW_YZ_RANK: "room_show_yz_rank",
    CALL_BUY_TICKET: "room_data_buytickets",
    CALL_ROOM_STATE: "room_data_state",
    ROOM_DATA_SHIDLIDAN: "room_data_ShieldDan",
    CALL_ROOM_DATA_HANDLER: "room_data_handler",
    CALL_ROOM_ACTIVITY_HANDLE: "room_activity_handle",
    CALL_ROOM_DATA_SHOPBROADCAST_CLICK: "room_shopBroadCast_click",
    CALL_ROOM_DATA_LOVE_HEADLINE: "room_data_love_headline",
    CALL_ROOM_DATA_LOGIN: "room_data_login",
    CALL_ROOM_DATA_INFO: "room_data_info",
    CALL_ROOM_DATA_USERC: "room_data_userc",
    CALL_ROOM_DATA_CHAT2: "room_data_chat2",
    CALL_ROOM_FOLLOW: "room_follow",
    CALL_ROOM_DATA_ILLCHANGE: "room_data_illchange",
    CALL_ROOM_DATA_IDLE: "room_data_idle",
    CALL_ROOM_DATA_IDLE_DP: "room_data_idle_dp",
    CALL_ROOM_CPS_SENDEXTENSIONBACK: "room_cps_SendExtensionBack",
    CALL_ROOM_DATA_ENDCHARGELIVE: "room_data_endchargelive",
    CALL_ROOM_DATA_ENDTRYSEE: "room_data_endtrysee",
    CALL_ROOM_DATA_CHARGELIVE: "room_data_chargelive",
    CALL_ROOM_DRAW_SEND_GIFT: "room_draw_send_gift",
    CALL_ROOM_SHOW_LOVE_HEADLINE: "room_show_love_headline",
    CALL_ROOM_DRAW_END: "room_draw_end",
    CALL_ROOM_DRAW_JOIN: "room_draw_join",
    CALL_ROOM_DRAW_STATUS: "room_draw_status",
    CALL_ROOM_DATA_CHEST: "room_data_chest",
    CALL_ROOM_DRAW_COPY_COMMAND: "room_draw_copy_command",
    CALL_CHARNGE: "room_chongnengv3",
    CALL_ROOM_DATA_REQ_GIFT_CONFIG: "room_data_req_gift_config",
    CALL_ROOM_DATA_FILTERKEYWORDS: "room_data_filterKeywords",
    CALL_ROOM_BUS_PHOCK: "room_bus_phock",
    CALL_ROOM_DATA_REG: "room_data_reg",
    CALL_ROOM_YZ_DATA: "room_yz_data",
    CALL_ROOM_YZ_BACKTIME: "room_yz_backtime",
    CALL_ROOM_YZ_END: "room_yz_end",
    CALL_ROOM_USERBAN: "room_user_ban",
    CALL_ROOM_VIDEO_CATCHTIME: "room_video_catchtime",
    ROOM_LOGIN_SHOW: "room_login_show",
    ROOM_REG_SHOW: "room_reg_show",
    ROOM_DATA_HIDESHOPBTN: "room_data_hideshopbtn",
    ROOM_DATA_CHATINIT: "room_data_chatinit",
    ROOM_DATA_SERERR: "room_data_sererr",
    ROOM_LOGIN_QUEUE: "room_login_queue",
    ROOM_DATA_SETADM: "room_data_setadm",
    ROOM_DATA_BROCAST: "room_data_brocast",
    ROOM_DATA_GIFT: "room_data_gift",
    ROOM_DATA_TASKLIS: "room_data_tasklis",
    ROOM_DATA_TASKCOU: "room_data_taskcou",
    ROOM_DATA_TASKREC: "room_data_taskrec",
    ROOM_DATA_TASKSIGN: "room_data_tasksign",
    ROOM_DATA_ONEKEYACC: "room_data_onekeyacc",
    ROOM_DATA_CHATREP: "room_data_chatrep",
    ROOM_DATA_LETTER: "room_data_letter",
    ROOM_DATA_YCCHANGE: "room_data_ycchange",
    ROOM_DATA_CHESTQUERY: "room_data_chestquery",
    ROOM_DATA_GIFTBAT1: "room_data_giftbat1",
    ROOM_DATA_EXPCHANGE: "room_data_expchange",
    ROOM_DATA_RANKGAP: "room_data_rankgap",
    ROOM_DATA_SYS: "room_data_sys",
    ROOM_DATA_CDEN: "room_data_cden",
    ROOM_RANK_LIST: "data_rank_list",
    ROOM_VIPSIT_LIST: "room_vipsit_list",
    ROOM_JIELONG_PROGRESS: "room_jielong_progress",
    ROOM_SHIELD_EFFECTS: "room_data_shield_effects",
    ROOM_DATA_NSTIP: "room_data_nstip",
    ROOM_DATA_NSTIP2: "room_data_nstip2",
    ROOM_DATA_BUYCQ: "room_data_buycq",
    ROOM_DATA_OLYW: "room_data_olyw",
    ROOM_DATA_SCAHT: "room_data_schat",
    ROOM_FRBINFO: "room_frbInfo",
    ROOM_DATA_GIFTBAT2: "room_data_giftbat2",
    ROOM_DATA_ULGROW: "room_data_ulgrow",
    ROOM_DATA_ULICO: "room_data_ulico",
    ROOM_DATA_ANCPOINTS: "room_data_ancpoints",
    ROOM_DATA_LUCKDRAWCD: "room_data_luckdrawcd",
    ROOM_DATA_SABONUS: "room_data_sabonus",
    ROOM_DATA_WBSHARESUC: "room_data_wbsharesuc",
    ROOM_DATA_SHARE_SUCCESS_RES: "room_data_share_success_res",
    ROOM_DATA_BURST: "room_data_burst",
    ROOM_BAPING_NOTIFY: "room_baping_notify",
    ROOM_DATA_COMMANDRESULT: "room_data_commandresult",
    ROOM_DATA_TBREDPACKET: "room_data_tbredpacket",
    ROOM_DATA_SABONUSGET: "room_data_sabonusget",
    ROOM_DATA_PAGEINFO: "room_data_pageinfo",
    DATA_RANK_NUM: "data_rank_num",
    DATA_RANK_SCORE: "data_rank_score",
    ROOM_DATA_FLAERR: "room_data_flaerr",
    ROOM_BUS_CHECKSERVERTIME: "room_bus_checksevertime",
    ROOM_DATA_PER: "room_data_per",
    ROOM_DATA_ADMFAIL: "room_data_admfail",
    ROOM_VIDEO_READY: "room_video_ready",
    ROOM_ADVERT_PLAYOVER: "room_advert_playover",
    ROOM_DATA_CQRANK: "room_data_cqrank",
    ROOM_DATA_CQRANK_UPDATE: "room_data_cqrankupdate",
    ROOM_SCREEN_CHANGE: "room_screenChange",
    ROOM_CAPTURE_WON_MOMENT: "room_capture_won_moment",
    ROOM_DATA_ATHENA_SUPERMSG: "room_data_athena_supermsg",
    ROOM_GCBROADCAST: "room_GCBroadCast_data",
    ROOM_SHOW_VALENTINE2018: "room_show_valentine2018",
    ROOM_SHOW_STARMAGIC: "room_show_starmagic",
    ROOM_SHOW_FOOLDAY2018: "room_show_foolday2018",
    ROOM_SHOW_HIT2018: "room_show_hit2018",
    ROOM_REBATE_STATUS: "room_rebate_status",
    ROOM_REBATE_END: "room_rebate_end",
    MROOM_VIDEO_END: "mroom_video_end",
    MROOM_JOIN_GROUP: "mroom_join_group",
    ROOM_PK_CONNECT: "room_pk_connect",
    ROOM_PK_END: "room_pk_end",
    ROOM_TCPCLIENT_FAILED: "room_tcpclient_failed",
    ROOM_TCPCLIENT_SUCCESS: "room_tcpclient_success",
    CALLBACK_PAGE_TYPE: "js_page_type",
    CALLBACK_BUYTICKETS_SUCCESS: "js_buytickets_success",
    CALLBACK_USER_NO_HANDLE: "js_UserNoHandle",
    CALLBACK_USER_HAVE_HANDLE: "js_UserHaveHandle",
    CALLBACK_USER_LOGIN: "js_userlogin",
    CALLBACK_USER_LOGOUT: "js_userlogout",
    CALLBACK_USER_SENDMSG: "js_sendmsg",
    CALLBACK_GAME_RECOMMEND: "js_game_recommend",
    CALLBACK_Command: "js_barrage_command",
    CALLBACK_CommandResult: "js_barrage_command_showresult",
    CALLBACK_JS_GIFT_CONFIG: "js_gift_config",
    CALLBACK_JS_FOLLOW_CHANGE: "js_follow_change",
    CALLBACK_JS_FANS_CHANGE: "js_fans_change",
    CALLBACK_JS_LUCKDRAW_END_FAIL: "js_luckdraw_end_fail",
    CALLBACK_JS_DRAW_JOIN: "js_draw_join",
    CALLBACK_JS_GIFT_LOVE_HEADLINE: "js_gift_love_headline",
    CALLBACK_PAGE_FULLSCREEN_STATE: "js_page_fullscreen_state",
    CALLBACK_BLACKLIST: "js_myblacklist",
    CALLBACK_INVITE_PK: "js_invite_PK",
    CALLBACK_GIVE_GIFT: "js_giveGift",
    CALLBACK_NEWUSER_CLIENT: "js_newuser_client",
    CALLBACK_USER_BLACKUSER: "js_blackuser",
    CALLBACK_SET_ADMIN: "js_setadmin",
    CALLBACK_GIVE_PRESENT: "js_givePresent",
    CALLBACK_QUERY_TASK: "js_queryTask",
    CALLBACK_NEWQUERY_TASK: "js_newQueryTask",
    CALLBACK_OBTAIN_TASK: "js_obtainTask",
    CALLBACK_ROOM_SIGNUP: "js_roomSignUp",
    CALLBACK_KEY_TITLES: "js_keyTitles",
    CALLBACK_REPORT_BARRAGE: "js_reportBarrage",
    CALLBACK_REWARD_LIST: "js_rewardList",
    CALLBACK_PM_FEEDBACK: "js_pmFeedback",
    CALLBACK_QUERY_GIFTPKG: "js_query_giftPkg",
    CALLBACK_SUPERDANMU_CLICK: "js_superDanmuClick",
    CALLBACK_GET_HONGBAO: "js_GetHongbao",
    CALLBACK_SHARE_SUCCESS: "js_shareSuccess",
    CALLBACK_GET_RANKSCORE: "js_getRankScore",
    CALLBACK_GET_NOBLE: "js_getnoble",
    CALLBACK_SEND_CATEMSG: "js_send_cate_msg",
    CALLBACK_JS_GMRDY: "js_gmrdy",
    CALLBACK_JS_GMST: "js_gmst",
    CALLBACK_MEDAL_OPERA: "js_medal_opera",
    CALLBACK_JS_SMDID: "js_callBack_SMDid",
    CALLBACK_ROOM_SPREAD: "js_room_spread",
    CALLBACK_SPREAD_SEARCH: "js_spread_search",
    CALLBACK_SERVER_SHIELD: "js_data_server_shield",
    CALLBACK_JS_SHIELDEFFECTS: "js_shieldEffects",
    CALLBACK_JS_sendHandle: "js_sendhandler",
    CALLBACK_JS_FILTERKERWORDS: "js_filterKeywords",
    CALLBACK_JS_BARRAGE: "js_barrage",
    CALLBACK_JS_EXIT_FULLSCREEN: "js_exitFullScreen",
    CALLBACK_JS_SEND_SUPER_DANMU: "js_send_super_danmu",
    CALLBACK_JS_BREAK_RULE_TIP: "js_breakRuleTip",
    CALLBACK_JS_CALL_EFFECT: "js_call_effect",
    CALLBACK_JS_SET_CAPTURE_SHOTCUTKEY: "js_set_capture_shotcutkey",
    CALLBACK_JS_GIFT_VALENTINE2018: "js_gift_valentine2018",
    CALLBACK_JS_GIFT_STARMAGIC: "js_gift_starmagic",
    CALLBACK_JS_SPRAY_INTERACT: "js_spray_interact",
    CALLBACK_JS_FANS_CONFIG: "js_fans_config",
    CALLBACK_JS_GIFT_FOOLDAY2018: "js_gift_foolday2018",
    CALLBACK_JS_GIFT_HIT2018: "js_gift_hit2018",
    CALLBACK_JS_REBATE_SEND_BACK: "js_rebate_send_back",
    CHATROOM_JOIN_SHOW: "chatroom_join_show",
    USER_JOIN_CHATROOM: "user_join_chatroom",
    CALL_CHATROOM_DATA_CHAT: "chatroom_data_chat",
    CALLBACK_CHATROOM_USER_SENDMSG: "chatroom_js_sendmsg",
    CHATROOM_QUIT_SHOW: "chatroom_quit_show",
    USER_QUIT_CHATROOM: "user_quit_chatroom",
    CHATROOM_HEART_SHOW: "chatroom_heart_show",
    USER_HEART_CHATROOM: "user_heart_chatroom"
}, {});